routes/web.php
<?php

use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\FormationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserFormationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('formations.index');
})->name('index');

Route::resource('formations', FormationController::class)->only(['index', 'show']);

Route::get('confirm-registration', AdminUserController::class)->name('confirm-registration');

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::name('user.')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [UserFormationController::class, 'index'])->name('index');
            Route::get('/create', [UserFormationController::class, 'create'])->name('create');
            Route::post('/store', [UserFormationController::class, 'store'])->name('store');
            Route::get('{formation}/edit', [UserFormationController::class, 'edit'])->name('edit');
            Route::put('{formation}/update', [UserFormationController::class, 'update'])->name('update');
            Route::get('{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });

        Route::name('profile.')->group(function () {
            Route::get('profile', [UserController::class, 'showProfil'])->name('show');
            Route::put('profile-update', [UserController::class, 'updateProfile'])->name('update');
            Route::put('password-update', [UserController::class, 'updatePassword'])->name('password-update');
        });
    });

    Route::name('admin.')->prefix('admin')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [FormationController::class, 'index'])->name('index');
            Route::get('/{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });
    });
});

Route::get('/test', function () {
    return view('layouts.email');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany as HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * App\Models\User.
 *
 * @property int $id
 * @property string $firstName
 * @property string $lastName
 * @property string $email
 * @property string $password
 * @property int $role_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\Laravel\Sanctum\PersonalAccessToken[] $tokens
 * @property-read int|null $tokens_count
 * @method static \Database\Factories\UserFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRoleId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The default user password.
     *
     * @var string
     */
    const DEFAULT_PASSWORD = 'password';

    /**
     *THe user Avatar file name Pattern.
     *
     * @var string
     */
    const AVATAR_IMAGE_NAME_PATTERN = 'avatar-?.?';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'firstName',
        'lastName',
        'email',
        'password',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        // 'remember_token',
    ];

    public function isAdmin()
    {
        return $this->role->name == UserRole::ADMIN_ROLE;
    }

    /**
     * Get all of the formations for the User.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function formation(): HasMany
    {
        return $this->hasMany(Formation::class, 'user_id', 'id');
    }

    /**
     * Get the role associated with the User.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role(): BelongsTo
    {
        return $this->belongsTo(UserRole::class, 'role_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdatePasswordRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function showProfil()
    {
        return view('users.profile');
    }

    public function updateProfile(UpdateProfileRequest $request)
    {
        $params = $request->validated();

        if ($email = $params['email']) {
            $user = User::find(auth()->user()->id);
            $user->email = $email;
            $user->save();
        }

        return redirect()->route('user.profile.show')->with(['success' => $email]);
    }

    public function updatePassword(UpdatePasswordRequest $request)
    {
        $params = $request->validated();

        $user = User::find(auth()->user()->id);

        $user->password = Hash::make($params['new_password']);

        $user->save();

        return redirect()->route('user.profile.show')->with(['success' => true]);
    }
}

resources/views/users/profile.blade.php
@extends('layouts.base')

@section('body')
    <div class="container-fluid px-6 py-4">
        <!-- row -->

        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-12 my-5">
                <!-- Bg -->
                <div class="pt-20 rounded-top"
                    style="background: url(../assets/images/background/profile-cover.jpg) no-repeat;background-size: cover;">
                </div>
                <div class="bg-white rounded-bottom smooth-shadow-sm ">
                    <div class="d-flex align-items-center justify-content-between
                      pt-4 pb-6 px-4">
                        <div class="d-flex align-items-center">
                            <!-- avatar -->
                            <div
                                class="avatar-xxl avatar-indicators avatar-online me-2
                          position-relative d-flex justify-content-end
                          align-items-end mt-n10">
                                <img src="../assets/images/avatar/avatar-1.jpg"
                                    class="avatar-xxl
                            rounded-circle border border-4 border-white-color-40"
                                    alt="">
                                <a href="#!" class="position-absolute top-0 right-0 me-2" data-bs-toggle="tooltip"
                                    data-placement="top" title="" data-original-title="Verified" data-bs-original-title="">
                                    <img src="../assets/images/svg/checked-mark.svg" alt="" width="30" height="30">
                                </a>
                            </div>
                            <!-- text -->
                            <div class="lh-1">
                                <h2 class="mb-0">
                                    <span
                                        style="font-weight: bold">{{ auth()->user()->lastName }}</span>&nbsp;{{ auth()->user()->firstName }}
                                    <a href="#!" class="text-decoration-none" data-bs-toggle="tooltip" data-placement="top"
                                        title="" data-original-title="Beginner" data-bs-original-title="">

                                    </a>
                                </h2>
                                <p class="mb-0 d-block">{{ auth()->user()->email }}</p>
                            </div>
                        </div>
                        <div>
                            <a href="{{ route('user.formations.index') }}"
                                class="btn btn-outline-primary d-none d-md-block">Tableau de bord</a>
                        </div>
                    </div>
                    <!-- nav -->
                </div>
            </div>
        </div>


        <!-- row -->
        <div class="row">

            @if (session()->has('success'))
                <div class="col-12">
                    <x-alert type="success" message="Votre profil a été mis à jour" />
                </div>
            @endif

            @if ($errors->any())
                <div class="col-12">
                    <x-alert type="danger" message="Veillez à bien remplir le formulaire" />
                </div>
            @endif

            <div class="col-12 mb-6">
                <!-- card -->
                <div class="card">
                    <!-- card body -->
                    <div class="card-body">
                        <div class="mb-6">
                            <h4 class="mb-1">Email</h4>
                        </div>
                        <form method="POST" action="{{ route('user.profile.update') }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')



                            <!-- row -->
                            <div class="mb-3 row">
                                <!-- label -->
                                <label for="newEmailAddress" class="col-sm-4 col-form-label form-label">Nouvelle addresse
                                    Email</label>
                                <div class="col-md-8 col-12">
                                    <!-- input -->
                                    <input name="email" type="email"
                                        class="form-control @error('email') is-invalid @enderror" placeholder="Nouveau mail"
                                        id="newEmailAddress" required value="{{ old('email', auth()->user()->email) }}">
                                    @error('email')
                                        <x-form-feedback type="invalid" :message="$message" />
                                    @enderror
                                </div>
                                <!-- button -->
                                <div class="offset-md-4 col-md-8 col-12 mt-3">
                                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
                                </div>
                            </div>
                        </form>

                        <div class="mb-6 mt-6">
                            <h4 class="mb-1">Changement de mot de passe</h4>

                        </div>
                        <form action="{{ route('user.profile.password-update') }}" method="POST">
                            <!-- row -->
                            @csrf
                            @method('PUT')
                            <div class="mb-3 row">
                                <label for="currentPassword" class="col-sm-4 col-form-label form-label">Mot de passe
                                    actuel</label>

                                <div class="col-md-8 col-12">
                                    <input name="password" type="password"
                                        class="form-control @error('password') is-invalid @enderror"
                                        placeholder="Mot de passe" id="currentPassword" required>
                                    @error('password')
                                        <x-form-feedback type="invalid" :message="$message" />
                                    @enderror
                                </div>
                            </div>
                            <!-- row -->
                            <div class="mb-3 row">
                                <label for="currentNewPassword" class="col-sm-4 col-form-label form-label">Nouveau mot de
                                    passe</label>

                                <div class="col-md-8 col-12">
                                    <input name="new_password" type="password"
                                        class="form-control @error('new_password') is-invalid @enderror"
                                        placeholder="Nouveau mot de passe" id="currentNewPassword" required>
                                    @error('new_password')
                                        <x-form-feedback type="invalid" :message="$message" />
                                    @enderror
                                </div>
                            </div>
                            <!-- row -->
                            <div class="row align-items-center">
                                <label for="confirmNewpassword" class="col-sm-4 col-form-label form-label">Confirmation du
                                    mot
                                    de passe</label>
                                <div class="col-md-8 col-12 mb-2 mb-lg-0">
                                    <input name="new_password_confirmation" type="password"
                                        class="form-control @error('new_password') is-invalid @enderror"
                                        placeholder="Nouveau mot de passe" id="confirmNewpassword" required>
                                </div>
                                <!-- list -->
                                <div class="offset-md-4 col-md-8 col-12 mt-4">
                                    {{-- <h6 class="mb-1">Password requirements:</h6>
                                    <p>Ensure that these requirements are met:</p>
                                    <ul>
                                        <li> Minimum 8 characters long the more, the better</li>
                                        <li>At least one lowercase character</li>
                                        <li>At least one uppercase character</li>
                                        <li>At least one number, symbol, or whitespace character
                                        </li>
                                    </ul> --}}
                                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/users/subscription-request-sucess.blade.php
@extends('layouts.base')

@section('body')
    <div class="container min-vh-100 d-flex justify-content-center
      align-items-center">
        <!-- row -->
        <div class="row">
            <!-- col -->
            <div class="col-12">
                <!-- content -->
                <div class="text-center">
                    <!-- text -->
                    <h1 class="display-4 fw-bold">Demande de compte Formateur envoyée !</h1>
                    <p class="mb-4">Votre demande d'accès pour un compte a été faite et sera traitée.
                        <br> Vous pouvez fermer cette pade ou accéder à la liste des formations.
                    </p>
                    <!-- button -->
                    <a href="{{ route('formations.index') }}" class="btn btn-primary">
                        <i class="bi bi-arrow-left-short"></i>
                        Consulter les formations
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/subsrciption-success.blade.php
@extends('layouts.base')

@section('body')
    <div class="container min-vh-100 d-flex justify-content-center
      align-items-center">
        <!-- row -->
        <div class="row">
            <!-- col -->
            <div class="col-12">
                <!-- content -->
                <div class="text-center">
                    <!-- text -->
                    <h1 class="display-4 fw-bold">Accès formateur accordé !</h1>
                    <p class="mb-4">Une demande d'accès pour un compte a été faite et viens d'être validée par
                        vous.<br> Vous pouvez fermer cette pade ou accéder à votre tableau de bord.</p>
                    <!-- button -->
                    <a href="{{ route('admin.formations.index') }}" class="btn btn-primary">
                        <i class="bi bi-house"></i>
                        Tableau de bord
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection