routes/web.php
<?php

use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\FormationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserFormationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('formations.index');
})->name('index');

Route::resource('formations', FormationController::class)->only(['index', 'show']);

Route::get('confirm-registration', AdminUserController::class)->name('confirm-registration');

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::name('user.')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [UserFormationController::class, 'index'])->name('index');
            Route::get('/create', [UserFormationController::class, 'create'])->name('create');
            Route::post('/store', [UserFormationController::class, 'store'])->name('store');
            Route::get('{formation}/edit', [UserFormationController::class, 'edit'])->name('edit');
            Route::put('{formation}/update', [UserFormationController::class, 'update'])->name('update');
            Route::get('{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });

        Route::name('profile.')->group(function () {
            Route::get('profile', [UserController::class, 'showProfil'])->name('show');
            Route::put('profile-update', [UserController::class, 'updateProfile'])->name('update');
            Route::put('password-update', [UserController::class, 'updatePassword'])->name('password-update');
        });
    });

    Route::name('admin.')->prefix('admin')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [FormationController::class, 'index'])->name('index');
            Route::get('/{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });
    });
});

Route::get('/test', function () {
    return view('layouts.email');
});

resources/views/layouts/admin/base.blade.php
@extends('layouts.base')

@section('body')
    <div id="db-wrapper">
        <!-- Sidebar -->
        @include('layouts.admin.sidebar')
        <!-- Page content -->
        <div id="page-content">

            <!-- navbar -->
            @include('layouts.admin.navbar')

            <!-- Container fluid -->
            @yield('container')
        </div>
    </div>
@endsection

@section('scripts')
    @auth
        <script>
            document.getElementById('logout-link').addEventListener('click', (event) => {
                document.querySelector('form#logout').submit();
            });
        </script>
    @endauth
    <script src="{{ asset('assets/js/admin.js') }}"></script>
@endsection

resources/views/layouts/admin/navbar.blade.php
<div class="header @@classList">
    <nav class="navbar-classic navbar navbar-expand-lg">
        <a id="nav-toggle" href="#"><i data-feather="menu" class="nav-icon me-2 icon-xs"></i></a>
        <div class="ms-lg-3 d-none d-md-none d-lg-block">
            <!-- Form -->
            <form class="d-flex align-items-center">
                <input type="search" class="form-control w-100" placeholder="Rechercher une formation..." />
            </form>
        </div>
        <!--Navbar nav -->
        @auth
        <ul class="navbar-nav navbar-right-wrap ms-auto d-flex nav-top-wrap">
            {{-- <li class="dropdown stopevent">
                <a class="btn btn-light btn-icon rounded-circle indicator indicator-primary text-muted" href="#"
                    role="button" id="dropdownNotification" data-bs-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="icon-xs" data-feather="bell"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end" aria-labelledby="dropdownNotification">
                    <div>
                        <div class="border-bottom px-3 pt-2 pb-3 d-flex justify-content-between align-items-center">
                            <p class="mb-0 text-dark fw-medium fs-4">Notifications</p>
                            <a href="#" class="text-muted">
                                <span>
                                    <i class="me-1 icon-xxs" data-feather="settings"></i>
                                </span>
                            </a>
                        </div>
                        <!-- List group -->
                        <ul class="list-group list-group-flush notification-list-scroll">
                            <!-- List group item -->
                            <li class="list-group-item bg-light">


                                <a href="#" class="text-muted">
                                    <h5 class="fw-bold mb-1">Rishi Chopra</h5>
                                    <p class="mb-0">
                                        Mauris blandit erat id nunc blandit, ac eleifend dolor pretium.
                                    </p>
                                </a>



                            </li>
                            <!-- List group item -->
                            <li class="list-group-item">


                                <a href="#" class="text-muted">
                                    <h5 class="fw-bold mb-1">Neha Kannned</h5>
                                    <p class="mb-0">
                                        Proin at elit vel est condimentum elementum id in ante. Maecenas et
                                        sapien metus.
                                    </p>
                                </a>



                            </li>
                            <!-- List group item -->
                            <li class="list-group-item">


                                <a href="#" class="text-muted">
                                    <h5 class="fw-bold mb-1">Nirmala Chauhan</h5>
                                    <p class="mb-0">
                                        Morbi maximus urna lobortis elit sollicitudin sollicitudieget elit
                                        vel pretium.
                                    </p>
                                </a>



                            </li>
                            <!-- List group item -->
                            <li class="list-group-item">


                                <a href="#" class="text-muted">
                                    <h5 class="fw-bold mb-1">Sina Ray</h5>
                                    <p class="mb-0">
                                        Sed aliquam augue sit amet mauris volutpat hendrerit sed nunc eu
                                        diam.
                                    </p>
                                </a>



                            </li>
                        </ul>
                        <div class="border-top px-3 py-2 text-center">
                            <a href="#" class="text-inherit fw-semi-bold">
                                View all Notifications
                            </a>
                        </div>
                    </div>
                </div>
            </li> --}}
            <!-- List -->
            <li class="dropdown ms-2">
                <a class="rounded-circle" href="#" role="button" id="dropdownUser" data-bs-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-md avatar-indicators avatar-online">
                        <img alt="avatar" src="{{ asset('assets/images/avatar/avatar-1.jpg') }}"
                            class="rounded-circle" />
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownUser">
                    <div class="px-4 pb-0 pt-2">
                        <div class="lh-1 ">
                            <h5 class="mb-1">{{ auth()->user()->lastName }}
                                {{ auth()->user()->firstName }} </h5>

                            <a href="{{ route('user.profile.show') }}" class="text-inherit fs-6">Mon profil <span
                                    class="fs-6 fst-italic">({{ auth()->user()->role->name }})</span></a>
                        </div>
                        <div class=" dropdown-divider mt-3 mb-2"></div>
                    </div>

                    <ul class="list-unstyled">
                        {{-- <li>
                            <a class="dropdown-item" href="#">
                                <i class="me-2 icon-xxs dropdown-item-icon" data-feather="user"></i>
                                Editer mon profil
                            </a>
                        </li> --}}

                        {{-- <li>
                            <a class="dropdown-item" href="#">
                                <i class="me-2 icon-xxs dropdown-item-icon" data-feather="settings"></i>Account
                                Settings
                            </a>
                        </li> --}}
                        <li>
                            <a id="logout-link" class="dropdown-item" href="#">
                                <i class="me-2 icon-xxs dropdown-item-icon" data-feather="power"></i>
                                Déconnexion
                            </a>
                            <form id="logout" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>

                </div>
            </li>
        </ul>
        @endauth
    </nav>
</div>

resources/views/layouts/admin/sidebar.blade.php
<nav class="navbar-vertical navbar">
    <div class="nav-scroller">
        <!-- Brand logo -->
        <a class="navbar-brand" @auth href="{{ route('user.formations.index') }}" @endauth @guest
            href="{{ route('formations.index') }}" @endguest>
            <!-- <img src="./assets/images/brand/logo/logo.svg" alt="" /> -->
            <span class="logo-text"> E-Formation</span>
        </a>
        <!-- Navbar nav -->
        <ul class="navbar-nav flex-column" id="sideNavbar">
            <!-- Nav item -->
            <li class="nav-item">
                <div class="navbar-heading">Administration</div>
            </li>
            <li class="nav-item">
                <a class="nav-link has-arrow  active " href="{{ route('user.formations.index') }}">
                    <i data-feather="lock" class="nav-icon icon-xs me-2"></i>
                    Tableau de bord
                </a>

            </li>


            <!-- Nav item -->
            <li class="nav-item">
                <div class="navbar-heading">Par Catégories</div>
            </li>


            <!-- Nav item -->
            <li class="nav-item">
                <a class="nav-link has-arrow  collapsed " href="#!" data-bs-toggle="collapse" data-bs-target="#navPages"
                    aria-expanded="false" aria-controls="navPages">
                    <i data-feather="layers" class="nav-icon icon-xs me-2">
                    </i> Catégories
                </a>

                <div id="navPages" class="collapse " data-bs-parent="#sideNavbar">
                    <ul class="nav flex-column">
                        @foreach ($categories as $category)
                        <li class="nav-item">
                            <a class="nav-link " href="./pages/profile.html">
                                {{ Str::of($category->name)->limit(20) }}
                            </a>
                        </li>
                        @endforeach
                    </ul>
                </div>

            </li>





        </ul>

    </div>
</nav>