routes/web.php
<?php

use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\FormationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserFormationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('formations.index');
})->name('index');

Route::resource('formations', FormationController::class)->only(['index', 'show']);

Route::get('confirm-registration', AdminUserController::class)->name('confirm-registration');

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::name('user.')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [UserFormationController::class, 'index'])->name('index');
            Route::get('/create', [UserFormationController::class, 'create'])->name('create');
            Route::post('/store', [UserFormationController::class, 'store'])->name('store');
            Route::get('{formation}/edit', [UserFormationController::class, 'edit'])->name('edit');
            Route::put('{formation}/update', [UserFormationController::class, 'update'])->name('update');
            Route::get('{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });

        Route::name('profile.')->group(function () {
            Route::get('profile', [UserController::class, 'showProfil'])->name('show');
            Route::put('profile-update', [UserController::class, 'updateProfile'])->name('update');
            Route::put('password-update', [UserController::class, 'updatePassword'])->name('password-update');
        });
    });

    Route::name('admin.')->prefix('admin')->group(function () {
        Route::name('formations.')->prefix('formations')->group(function () {
            Route::get('/', [FormationController::class, 'index'])->name('index');
            Route::get('/{formation}/destroy', [UserFormationController::class, 'destroy'])->name('destroy');
        });
    });
});

Route::get('/test', function () {
    return view('layouts.email');
});

app/Models/Formation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo as BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany as BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany as HasMany;
use Illuminate\Support\Facades\Cache;

/**
 * App\Models\Formation.
 *
 * @property int $id
 * @property string $designation
 * @property string $description
 * @property string $type
 * @property string $image
 * @property string $price
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Database\Factories\FormationFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Formation newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Formation query()
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereDesignation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Formation whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Formation extends Model
{
    use HasFactory;

    /**
     * The Formation image name pattern.
     *
     * @var string
     */
    const IMAGE_PATTERN = 'image-formations-?.?';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'formations';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'designation',
        'description',
        'type',
        'image',
        'price',
    ];

    public static function boot()
    {
        parent::boot();
        self::deleting(function ($formation) { // before delete() method call this
            $formation->chapters()->each(function ($chapter) {
                $chapter->delete(); // <-- direct deletion
            });

            $formation->categoryLinks()->each(function ($link) {
                $link->delete();
            });
            // do the rest of the cleanup...
        });
    }

    /**
     * Get the user that owns the Formation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    /**
     * Get all of the chapters for the Formation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function chapters(): HasMany
    {
        return $this->hasMany(Chapter::class, 'formation_id', 'id');
    }

    /**
     * Get all of the links to categories for the Formation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function categoryLinks(): HasMany
    {
        return $this->hasMany(FormationCategoryLink::class, 'formation_id', 'id');
    }

    /**
     * The categories that belong to the Formation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Cache::class, 'formations_categories', 'formation_id', 'category_id');
    }
}

app/Http/Controllers/FormationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Formation;

class FormationController extends Controller
{
    public function index()
    {
        $formations = Formation::with(['user'])->paginate(15);
        $categories = Category::all();

        return view('formations.index', compact(['formations', 'categories']));
    }

    public function show($formation)
    {
        $formation = Formation::find($formation);
        $categories = Category::all();

        return view('formations.show', compact(['formation', 'categories']));
    }
}

resources/views/formations/create.blade.php
@extends('layouts.admin.base')

@section('container')
    <div class="container">
        <div class="row my-5">
            @if ($errors->any())
                <div class="col-12 my-2">
                    <x-alert type="danger" message="Veillez à bien remplir le formulaire" />
                </div>
            @endif

            <div class="card">
                <div class="card-body">
                    <div class="card mb-3">
                        <img src="{{ asset('assets/images/placeholder/placeholder-4by3.svg') }}" class="card-img-bottom"
                            alt="...">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <form id="add-formation" method="POST" action="{{ route('user.formations.store') }}"
                                        enctype="multipart/form-data">
                                        @csrf
                                        <!-- Input -->
                                        <div class="mb-3">
                                            <label class="form-label" for="textInput">Désignation</label>
                                            <input type="text" id="textInput"
                                                class="form-control @error('designation') is-invalid @enderror"
                                                name="designation" placeholder="Désingation">
                                            @error('designation')
                                                <x-form-feedback type="invalid" :message="$message" />
                                            @enderror
                                        </div>
                                        <!-- Input -->
                                        <div class="mb-3">
                                            <label class="form-label" for="textInput">Image</label>
                                            <input type="file" class="form-control @error('image') is-invalid @enderror"
                                                name="image" accept="image/png image/jpg image/jpeg">
                                            @error('image')
                                                <x-form-feedback type="invalid" :message="$message" />
                                            @enderror
                                        </div>
                                        <!-- Text Area -->
                                        <div class="mb-3">
                                            <label class="form-label" for="textareaInput">Description</label>
                                            <textarea name="description" id="description"
                                                class="form-control @error('description') is-invalid @enderror"
                                                placeholder="Détail de la formation ici..." rows="4"></textarea>
                                            @error('description')
                                                <x-form-feedback type="invalid" :message="$message" />
                                            @enderror
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Prix(€)</label>
                                            <input class="form-control @error('price') is-invalid @enderror" type="number"
                                                min="0" step="0.10" value="0" name="price" />
                                            @error('price')
                                                <x-form-feedback type="invalid" :message="$message" />
                                            @enderror
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Nombre de chapitre</label>
                                            <input id="chapter-nb"
                                                class="form-control @error('chapters') is-invalid @enderror" type="number"
                                                min="1" step="1" value="1" />
                                            @error('chapters')
                                                <x-form-feedback type="invalid" :message="$message" />
                                            @enderror
                                        </div>
                                        <div id="chapter-zone">
                                            <!-- Input -->
                                            <div class="mb-3">
                                                <label class="form-label" for="textInput">Chapitre 1</label>
                                                <input type="text" id="textInput" class="form-control" name="chapters[]"
                                                    placeholder="Titre du chapitre...">
                                            </div>
                                        </div>
                                        <p><label>Catégories</label></p>
                                        <!-- Select Option -->
                                        @error('categories')
                                            <p class="invalid-feedback d-block">{{ $message }}</p>
                                        @enderror
                                        @foreach ($categories as $category)
                                            <div class="form-check form-check-inline">
                                                <input name="categories[]" class="form-check-input" type="checkbox"
                                                    id="inlineCheckbox1" value="{{ $category->id }}">
                                                <label class="form-check-label"
                                                    for="inlineCheckbox1">{{ $category->name }}</label>
                                            </div>
                                        @endforeach
                                        <div class="col-12 my-3 text-center">
                                            <button id='submit-form' class="btn btn-primary" type="submit">Ajouter la
                                                formation</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="https://cdn.tiny.cloud/1/4741oc33ybtlzv6rsed459tfil3q25ivwfmvcieq3g5wocus/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script>
        window.addEventListener('load', (event) => {
            tinymce.init({
                selector: '#description'
            });
        });
    </script>

    <script>
        document.getElementById('chapter-nb').addEventListener('change', (event) => {
            const chapterNb = event.currentTarget.value;
            const chapterZone = document.getElementById('chapter-zone');

            chapterZone.innerHTML = '';

            for (let i = 1; i <= chapterNb; i++) {
                chapterZone.innerHTML += `<div class="mb-3">
                                                <label class="form-label" for="textInput">Chapitre ${i}</label>
                                                <input type="text" id="textInput" class="form-control" name="chapters[]"
                                                    placeholder="Titre du chapitre...">
                                            </div>`;
            }
        });
    </script>
@endsection

resources/views/formations/edit.blade.php
@extends('layouts.admin.base')

@section('container')
<div class="container">
    <div class="row my-5">
        @if ($errors->any())
        <div class="col-12 my-2">
            <x-alert type="danger" message="Veillez à bien remplir le formulaire" />
        </div>
        @endif

        <div class="card">
            <div class="card-body">
                <div class="card mb-3">
                    <img src="@if (Str::contains($formation->image, 'https')){{ asset($formation->image) }}@else{{ asset('storage/' . $formation->image) }}@endif"
                        height="800px" class="card-img-bottom" alt="...">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <form id="edit-formation" method="POST" action="{{ route('user.formations.update',
                                    ['formation' => $formation->id, 'id' => $formation->id]) }}"
                                    enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <!-- Input -->
                                    <div class="mb-3">
                                        <label class="form-label" for="textInput">Désignation</label>
                                        <input type="text" id="textInput"
                                            class="form-control @error('designation') is-invalid @enderror"
                                            name="designation" placeholder="Désingation"
                                            value="{{ $formation->designation }}">
                                        @error('designation')
                                        <x-form-feedback type="invalid" :message="$message" />
                                        @enderror
                                    </div>
                                    <!-- Input -->
                                    <div class="mb-3">
                                        <label class="form-label" for="textInput">Image</label>
                                        <input type="file" class="form-control @error('image') is-invalid @enderror"
                                            name="image" accept="image/png image/jpg image/jpeg">
                                        @error('image')
                                        <x-form-feedback type="invalid" :message="$message" />
                                        @enderror
                                    </div>
                                    <!-- Text Area -->
                                    <div class="mb-3">
                                        <label class="form-label" for="textareaInput">Description</label>
                                        <textarea name="description" id="description"
                                            class="form-control @error('description') is-invalid @enderror"
                                            placeholder="Détail de la formation ici..."
                                            rows="4">{!! $formation->description !!}</textarea>
                                        @error('description')
                                        <x-form-feedback type="invalid" :message="$message" />
                                        @enderror
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label">Prix(€)</label>
                                        <input class="form-control @error('price') is-invalid @enderror" type="number"
                                            min="0" step="0.10" value="0" name="price"
                                            value="{{ $formation->price }}" />
                                        @error('price')
                                        <x-form-feedback type="invalid" :message="$message" />
                                        @enderror
                                    </div>

                                    <div class="mb-3">
                                        <label class="form-label">Nombre de
                                            chapitre</label>
                                        <input id="chapter-nb"
                                            class="form-control @error('chapters') is-invalid @enderror" type="number"
                                            min="1" step="1" value="{{ $formation->chapters->count() }}" />

                                        @error('chapters')
                                        <x-form-feedback type="invalid" :message="$message" />
                                        @enderror
                                    </div>
                                    <div id="chapter-zone">
                                        <!-- Input -->
                                        @foreach ($formation->chapters as $chapter)
                                        <div class="mb-3">
                                            <label class="form-label" for="textInput">Chapitre
                                                {{ $loop->index + 1 }}</label>
                                            <input type="text" id="textInput" class="form-control" name="chapters[]"
                                                value="{{ $chapter->title }}" placeholder="Titre du chapitre...">
                                        </div>
                                        @endforeach
                                    </div>
                                    <p><label>Catégories</label></p>
                                    <!-- Select Option -->
                                    @error('categories')
                                    <p class="invalid-feedback d-block">{{ $message }}</p>
                                    @enderror
                                    @foreach ($categories as $category)
                                    <div class="form-check form-check-inline">
                                        <input name="categories[]" class="form-check-input" type="checkbox"
                                            id="inlineCheckbox1" value="{{ $category->id }}">
                                        <label class="form-check-label" for="inlineCheckbox1">{{ $category->name
                                            }}</label>
                                    </div>
                                    @endforeach
                                    <div class="col-12 my-3 text-center">
                                        <button id='submit-form' class="btn btn-primary" type="submit">Modifier la
                                            formation</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('scripts')
<script src="https://cdn.tiny.cloud/1/4741oc33ybtlzv6rsed459tfil3q25ivwfmvcieq3g5wocus/tinymce/5/tinymce.min.js"
    referrerpolicy="origin"></script>
<script>
    window.addEventListener('load', (event) => {
        tinymce.init({
            selector: '#description'
        });
    });
</script>

<script>
    document.getElementById('chapter-nb').addEventListener('change', (event) => {
        const chapterNb = event.currentTarget.value;
        const chapterZone = document.getElementById('chapter-zone');

        chapterZone.innerHTML = '';

        for (let i = 1; i <= chapterNb; i++) {
            chapterZone.innerHTML += `<div class="mb-3">
                                                <label class="form-label" for="textInput">Chapitre ${i}</label>
                                                <input type="text" id="textInput" class="form-control" name="chapters[]"
                                                    placeholder="Titre du chapitre...">
                                            </div>`;
        }
    });
</script>
@endsection

resources/views/formations/index.blade.php
@extends('layouts.admin.base')

@section('container')
    <div class="bg-primary pt-10 pb-21"></div>
    <div class="container-fluid mt-n22 px-6">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-12">
                <!-- Page header -->
                <div>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="mb-2 mb-lg-0">
                            <h3 class="mb-0 fw-bold text-white">Formations</h3>
                        </div>
                        @auth
                            <div>
                                <a href="{{ route('user.formations.create') }}" class="btn btn-white">Ajouter une
                                    formation</a>
                            </div>
                        @endauth
                    </div>
                </div>
            </div>
            @auth
                <div class="col-xl-3 col-lg-6 col-md-12 col-12 mt-6">
                    <!-- card -->
                    <div class="card rounded-3">
                        <!-- card body -->
                        <div class="card-body">
                            <!-- heading -->
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div>
                                    <h4 class="mb-0">Formations</h4>
                                </div>
                                <div class="icon-shape icon-md bg-light-primary text-primary rounded-1">
                                    <i class="bi bi-briefcase fs-4"></i>
                                </div>
                            </div>
                            <!-- project number -->
                            <div>
                                <h1 class="fw-bold">{{ $formations->count() }}</h1>
                                <p class="mb-0"><span class="text-dark me-2">2</span>Completed</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-12 col-12 mt-6">
                    <!-- card -->
                    <div class="card rounded-3">
                        <!-- card body -->
                        <div class="card-body">
                            <!-- heading -->
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div>
                                    <h4 class="mb-0">Active Task</h4>
                                </div>
                                <div class="icon-shape icon-md bg-light-primary text-primary rounded-1">
                                    <i class="bi bi-list-task fs-4"></i>
                                </div>
                            </div>
                            <!-- project number -->
                            <div>
                                <h1 class="fw-bold">132</h1>
                                <p class="mb-0"><span class="text-dark me-2">28</span>Completed</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-12 col-12 mt-6">
                    <!-- card -->
                    <div class="card rounded-3">
                        <!-- card body -->
                        <div class="card-body">
                            <!-- heading -->
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div>
                                    <h4 class="mb-0">Teams</h4>
                                </div>
                                <div class="icon-shape icon-md bg-light-primary text-primary rounded-1">
                                    <i class="bi bi-people fs-4"></i>
                                </div>
                            </div>
                            <!-- project number -->
                            <div>
                                <h1 class="fw-bold">12</h1>
                                <p class="mb-0"><span class="text-dark me-2">1</span>Completed</p>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-xl-3 col-lg-6 col-md-12 col-12 mt-6">
                    <!-- card -->
                    <div class="card rounded-3">
                        <!-- card body -->
                        <div class="card-body">
                            <!-- heading -->
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div>
                                    <h4 class="mb-0">Productivity</h4>
                                </div>
                                <div class="icon-shape icon-md bg-light-primary text-primary rounded-1">
                                    <i class="bi bi-bullseye fs-4"></i>
                                </div>
                            </div>
                            <!-- project number -->
                            <div>
                                <h1 class="fw-bold">76%</h1>
                                <p class="mb-0"><span class="text-success me-2">5%</span>Completed</p>
                            </div>
                        </div>
                    </div>
                </div>
            @endauth
        </div>
        <!-- row  -->
        <div class="row mt-6">
            <!-- table  -->
            <div class="card-body">
                <div class="row">
                    @foreach ($formations as $formation)
                        <div class="col-4 my-5">
                            <div class="card position-relative">
                                <img src="@if (Str::contains($formation->image, 'https')){{ asset(" $formation->image") }}@else{{ asset("storage/$formation->image") }}@endif" height="400px" class="card-img-top"
                                    alt="{{ $formation->designation }}">

                                <span class="badge rounded-pill bg-primary position-absolute fs-5 shadow"
                                    style="top: 5px; right: 5px;">{{ $formation->price }} €</span>
                                <div class="card-body text-center">
                                    <h5 class="card-title fw-bolder fs-4 my-2">{{ $formation->designation }}</h5>
                                    <a href="{{ route('formations.show', ['formation' => $formation->id]) }}"
                                        class="btn btn-primary">
                                        <i class="bi bi-eye-fill"></i>&nbsp;Suivre
                                    </a>
                                    @auth
                                        @if ($formation->user()->is(auth()->user()) ||
            auth()->user()->isAdmin())
                                            <a href="{{ route('user.formations.edit', ['formation' => $formation->id]) }}"
                                                class="btn btn-primary">
                                                <span class="bi bi-pen-fill"></span> Editer</a>
                                            <a id="formation-delete"
                                                href="{{ route('user.formations.destroy', ['formation' => $formation->id]) }}"
                                                class="btn btn-primary">
                                                <span class="bi bi-trash-fill"></span> Retirer</a>
                                        @endif
                                    @endauth
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                {{-- <p href="#">{{ $formations->links() }}</p> --}}
            </div>
            <!-- card footer  -->


        </div>
    </div>

@endsection